version: '3'
services:
  nestjs-app-node:
    build:
      context: docker/node
    container_name: nestjs-app-node
    volumes:
      - ./app:/var/www
    tty: true
    depends_on:
      - nestjs-app-postgres
    ports:
    - "3000:3000"
    networks:
      - internal
  nestjs-app-postgres:
    image: postgres:12-alpine
    container_name: nestjs-app-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nestjs
    ports:
      - "5432:5432"
    networks:
      - internal
  nestjs-app-mailer:
    container_name: nestjs-app-mailer
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - internal
  nestjs-app-redis:
    container_name: nestjs-app-redis
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
    networks:
      - internal
  nestjs-app-centrifugal:
    container_name: nestjs-app-centrifugal
    image: centrifugo/centrifugo
    command: centrifugo -c config.json --engine=redis --redis_url=redis://nestjs-app-redis:6379/13
    ports:
      - "8000:8000"
    volumes:
      - "./docker/centrifugo:/centrifugo"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - nestjs-app-redis
    networks:
      - internal
volumes:
  postgres-data:
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.225.0/24